ktmitton/Mittons.Fixtures

Mittons.Fixtures.Tests.Unit/Docker/Containers/SftpContainerTests.cs, Mittons.Fixtures/Docker/Containers/SftpContainer.cs, Mittons.Fixtures/Models/SftpUserAccount.cs
Created the Sftp container.
Implements #3
=> Implemented the SftpContainer

Mittons.Fixtures.Tests.Integration/Docker/Gateways/DefaultDockerGatewayTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Containers/ContainerTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Containers/SftpContainerTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Fixtures/DockerEnvironmentTests.cs, Mittons.Fixtures/Docker/Containers/Container.cs, Mittons.Fixtures/Docker/Containers/SftpContainer.cs, Mittons.Fixtures/Docker/Gateways/DefaultDockerGateway.cs, Mittons.Fixtures/Docker/Gateways/IDockerGateway.cs
Implemented NetworkCreate, NetworkRemove, NetworkConnect
Added ability to get the IP address for a container on startup so it can be accessed by the host environment
Implements #10 
Implements #5
=> Ip address

Mittons.Fixtures.Tests.Unit/Docker/Containers/ContainerTests.cs, Mittons.Fixtures/Docker/Containers/Container.cs, Mittons.Fixtures/Docker/Gateways/DefaultDockerGateway.cs, Mittons.Fixtures/Docker/Gateways/IDockerGateway.cs
Added the generic file management, still need to implement the actual gateway functions.
#13
=> Added file management to gateway and the container

Mittons.Fixtures.Tests.Integration/Docker/Gateways/DefaultDockerGatewayTests.cs, Mittons.Fixtures/Docker/Gateways/DefaultDockerGateway.cs
Implements the add file functionality of the default docker gateway, we still need to implement the remove file.
Implements #13
=> Implemented add file functionality

Mittons.Fixtures.Tests.Integration/Docker/Gateways/DefaultDockerGatewayTests.cs, Mittons.Fixtures/Docker/Gateways/DefaultDockerGateway.cs
Implemented the removeFile
Implements #13
=> Implemented remove file in the default docker gateway

Mittons.Fixtures.Tests.Integration/Docker/Fixtures/DockerEnvironmentFixtureTests.cs, Mittons.Fixtures/Docker/Fixtures/DockerEnvironmentFixture.cs, Mittons.Fixtures/Mittons.Fixtures.csproj
* Implemented parameter-less constructor
* Created a test of IClassFixture with the environment
Implements #17
=> Added parameter-less constructor

Mittons.Fixtures.Tests.Integration/Docker/Fixtures/DockerEnvironmentFixtureTests.cs, Mittons.Fixtures.Tests.Integration/Docker/Gateways/DefaultDockerGatewayTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Fixtures/DockerEnvironmentTests.cs, Mittons.Fixtures/Docker/Attributes/Run.cs, Mittons.Fixtures/Docker/Fixtures/DockerEnvironmentFixture.cs, Mittons.Fixtures/Docker/Gateways/DefaultDockerGateway.cs, Mittons.Fixtures/Docker/Gateways/IDockerGateway.cs, Mittons.Fixtures/Docker/Networks/DefaultNetwork.cs
Implemented runs on networks
Implements #18
=> Network labels

Mittons.Fixtures.Tests.Integration/Docker/Fixtures/DockerEnvironmentFixtureTests.cs, Mittons.Fixtures.Tests.Integration/Docker/Gateways/DefaultDockerGatewayTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Containers/ContainerTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Containers/SftpContainerTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Fixtures/DockerEnvironmentTests.cs, Mittons.Fixtures/Docker/Containers/Container.cs, Mittons.Fixtures/Docker/Fixtures/DockerEnvironmentFixture.cs, Mittons.Fixtures/Docker/Gateways/DefaultDockerGateway.cs, Mittons.Fixtures/Docker/Gateways/IDockerGateway.cs
Adds run labels to containers
Implements #18
=> Container labels

Mittons.Fixtures.Tests.Integration/Docker/Gateways/DefaultDockerGatewayTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Containers/SftpContainerTests.cs, Mittons.Fixtures/Docker/Containers/SftpContainer.cs, Mittons.Fixtures/Docker/Gateways/DefaultDockerGateway.cs, Mittons.Fixtures/Docker/Gateways/IDockerGateway.cs, Mittons.Fixtures/Models/Fingerprint.cs, Mittons.Fixtures/Models/SftpConnectionsSettings.cs
Added SftpConnectionSettings
Added ability to get host port mappings
Added ability to execute commands against a container
Implements #23
=> Added sftp connection settings to the sftp container

Mittons.Fixtures.Tests.Integration/Docker/Gateways/DefaultDockerGatewayTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Containers/ContainerTests.cs, Mittons.Fixtures/Docker/Containers/Container.cs, Mittons.Fixtures/Docker/Gateways/DefaultDockerGateway.cs, Mittons.Fixtures/Docker/Gateways/IDockerGateway.cs, Mittons.Fixtures/Resource/IServiceLifetime.cs
Initial implementation of the start async function
Implements #28
=> Created initial implementation of StartAsync

Mittons.Fixtures.Tests.Integration/Docker/Gateways/DefaultDockerGatewayTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Containers/ContainerTests.cs, Mittons.Fixtures/Docker/Containers/Container.cs, Mittons.Fixtures/Docker/Gateways/DefaultDockerGateway.cs, Mittons.Fixtures/Docker/Gateways/IDockerGateway.cs, Mittons.Fixtures/Extensions/CancellationTokenExtensions.cs
Updated removeFile to be async
Addresses #28
=> Updated removeFile to be async

Mittons.Fixtures.Tests.Integration/Docker/Gateways/DefaultDockerGatewayTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Containers/ContainerTests.cs, Mittons.Fixtures/Docker/Containers/Container.cs, Mittons.Fixtures/Docker/Gateways/DefaultDockerGateway.cs, Mittons.Fixtures/Docker/Gateways/IDockerGateway.cs
Updated addfile to be async
Implements #28
=> Updated addfile to be async

Mittons.Fixtures.Tests.Integration/Docker/Gateways/DefaultDockerGatewayTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Containers/SftpContainerTests.cs, Mittons.Fixtures/Docker/Containers/SftpContainer.cs, Mittons.Fixtures/Docker/Gateways/DefaultDockerGateway.cs, Mittons.Fixtures/Docker/Gateways/IDockerGateway.cs
Updated host port mapping to be async.
Implements #28
=> Converted host port mapping to async

Mittons.Fixtures.Tests.Integration/Docker/Gateways/DefaultDockerGatewayTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Fixtures/DockerEnvironmentTests.cs, Mittons.Fixtures/Docker/Gateways/DefaultDockerGateway.cs, Mittons.Fixtures/Docker/Gateways/IDockerGateway.cs, Mittons.Fixtures/Docker/Networks/DefaultNetwork.cs
Updated network remove to be async
Implements #28
=> Updated network remove to be async

Mittons.Fixtures.Tests.Integration/Docker/Gateways/DefaultDockerGatewayTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Fixtures/DockerEnvironmentTests.cs, Mittons.Fixtures/Docker/Fixtures/DockerEnvironmentFixture.cs, Mittons.Fixtures/Docker/Gateways/DefaultDockerGateway.cs, Mittons.Fixtures/Docker/Gateways/IDockerGateway.cs
Updated network connect to be async
Implements #28
=> Updated network connect to be async

Mittons.Fixtures.Tests.Integration/Docker/Gateways/DefaultDockerGatewayTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Containers/ContainerTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Fixtures/DockerEnvironmentTests.cs, Mittons.Fixtures/Docker/Containers/Container.cs, Mittons.Fixtures/Docker/Gateways/DefaultDockerGateway.cs, Mittons.Fixtures/Docker/Gateways/IDockerGateway.cs
Updated container remove to be async
Implements #28
=> Updated container remove to be async

Mittons.Fixtures.Tests.Integration/Docker/Gateways/DefaultDockerGatewayTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Containers/SftpContainerTests.cs, Mittons.Fixtures/Docker/Containers/SftpContainer.cs, Mittons.Fixtures/Docker/Gateways/DefaultDockerGateway.cs, Mittons.Fixtures/Docker/Gateways/IDockerGateway.cs
Updated container execute to be async\
Implements #28
=> Updated container execute to be async

Mittons.Fixtures.Tests.Integration/Docker/Gateways/DefaultDockerGatewayTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Fixtures/DockerEnvironmentTests.cs, Mittons.Fixtures/Docker/Gateways/DefaultDockerGateway.cs, Mittons.Fixtures/Docker/Gateways/IDockerGateway.cs, Mittons.Fixtures/Docker/Networks/DefaultNetwork.cs
Implemented network create as async
Implements #28
=> Implemented network create as async

Mittons.Fixtures.Tests.Integration/Docker/Gateways/DefaultDockerGatewayTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Containers/ContainerTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Containers/SftpContainerTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Fixtures/DockerEnvironmentTests.cs, Mittons.Fixtures/Docker/Containers/Container.cs, Mittons.Fixtures/Docker/Gateways/DefaultDockerGateway.cs, Mittons.Fixtures/Docker/Gateways/IDockerGateway.cs
Updated default network ip address retrieval to async
Implements #28
=> Updated default network ip address retrieval to async

Mittons.Fixtures.Tests.Integration/Docker/Gateways/DefaultDockerGatewayTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Containers/ContainerTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Containers/SftpContainerTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Fixtures/DockerEnvironmentTests.cs, Mittons.Fixtures/Docker/Containers/Container.cs, Mittons.Fixtures/Docker/Gateways/DefaultDockerGateway.cs, Mittons.Fixtures/Docker/Gateways/IDockerGateway.cs
Updated container run to be async
Implements #28
=> Updated container run to be async

Mittons.Fixtures.Tests.Unit/Docker/Containers/ContainerTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Containers/SftpContainerTests.cs, Mittons.Fixtures/Docker/Containers/Container.cs, Mittons.Fixtures/Docker/Containers/SftpContainer.cs, Mittons.Fixtures/Docker/Fixtures/DockerEnvironmentFixture.cs, Mittons.Fixtures/Mittons.Fixtures.csproj
Updated containers to implement InitializeAsync
Implements #28
=> Updated containers to implement InitializeAsync

Mittons.Fixtures.Tests.Unit/Docker/Containers/ContainerTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Containers/SftpContainerTests.cs, Mittons.Fixtures/Docker/Containers/Container.cs, Mittons.Fixtures/Docker/Fixtures/DockerEnvironmentFixture.cs, Mittons.Fixtures/Mittons.Fixtures.csproj
Updated containers to use async dispose
Implements #28
=> Updated containers to use async dispose

Mittons.Fixtures.Tests.Integration/Docker/Gateways/DefaultDockerGatewayTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Containers/SftpContainerTests.cs, Mittons.Fixtures/Docker/Containers/SftpContainer.cs
Replaced getawaiters with await
Implements #28
=> Replaced getawaiters with await

Mittons.Fixtures.Tests.Integration/Docker/Gateways/DefaultDockerGatewayTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Containers/ContainerTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Containers/SftpContainerTests.cs, Mittons.Fixtures/Docker/Gateways/DefaultDockerGateway.cs
Removed more getawaiters
Implements #28
=> Removed more getawaiters

Mittons.Fixtures/Docker/Fixtures/DockerEnvironmentFixture.cs, Mittons.Fixtures/Docker/Networks/DefaultNetwork.cs
Updated networks to async lifetime
Implements #28
=> Updated networks to async lifetime

Mittons.Fixtures.Tests.Unit/Docker/Containers/ContainerTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Containers/SftpContainerTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Fixtures/DockerEnvironmentTests.cs, Mittons.Fixtures/Docker/Containers/Container.cs, Mittons.Fixtures/Docker/Containers/SftpContainer.cs, Mittons.Fixtures/Docker/Fixtures/DockerEnvironmentFixture.cs
Updated the fixture to implement IAsyncLifetime
Implements #28
=> Fixture async

Mittons.Fixtures/Mittons.Fixtures.csproj
updated proj file to allow packing
=> updated proj file to allow packing

Mittons.Fixtures.Tests.Unit/Docker/Containers/ContainerTests.cs
Grouped tests so they are more organized and easily collapsible
Will be helpful for #53
=> Reorganized the container tests

Mittons.Fixtures.Tests.Unit/Docker/Containers/ContainerTests.cs, Mittons.Fixtures/Docker/Attributes/HealthCheck.cs, Mittons.Fixtures/Docker/Attributes/IOptionAttribute.cs, Mittons.Fixtures/Docker/Attributes/Run.cs, Mittons.Fixtures/Docker/Containers/Container.cs
Added the health check attribute, next step is to integrate it into the sftp container.
Needed for #53
=> Added health check attribute

Mittons.Fixtures.Tests.Unit/Docker/Containers/BaseContainerTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Containers/ContainerTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Containers/SftpContainerTests.cs
=> Grouped sftp container tests for easier organization

Mittons.Fixtures.Tests.Unit/Docker/Containers/SftpContainerTests.cs, Mittons.Fixtures/Docker/Containers/SftpContainer.cs
Added the default health check to the sftp container
Completes #53
=> Added the default health check to the sftp container

.github/workflows/run-automated-tests.yml, Mittons.Fixtures.Example/Fixtures/ReportingEnvironmentFixture.cs, Mittons.Fixtures.Example/Mittons.Fixtures.Example.csproj, Mittons.Fixtures.Example/Sftp/ConnectionTests.cs, Mittons.Fixtures.Tests.Integration/Docker/Gateways/DefaultDockerGatewayTests.cs, Mittons.Fixtures.sln, Mittons.Fixtures/Docker/Gateways/DefaultDockerGateway.cs
=> Added example project

Mittons.Fixtures.Example/Sftp/ConnectionTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Containers/SftpContainerTests.cs, Mittons.Fixtures/Docker/Containers/SftpContainer.cs
Added wrapper function to the sftp container so you can add files directly to a user's directory.
=> Sftp file management

Mittons.Fixtures.Example/Fixtures/ReportingEnvironmentFixture.cs, Mittons.Fixtures.Example/Sftp/ConnectionTests.cs, Mittons.Fixtures.Tests.Integration/Docker/Fixtures/DockerEnvironmentFixtureTests.cs, Mittons.Fixtures.Tests.Integration/Docker/Gateways/DefaultDockerGatewayTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Containers/BaseContainerTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Containers/ContainerTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Containers/SftpContainerTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Fixtures/DockerEnvironmentTests.cs, Mittons.Fixtures/Docker/Containers/SftpContainer.cs, Mittons.Fixtures/Docker/Fixtures/DockerEnvironmentFixture.cs
- Adding readonly access modifier to private fields set in constructors.
- For projects targeting .NET 6 and C# 10 language version, suggesting the shift to file-scoped namespaces.
=> Some Minor Suggestions

Mittons.Fixtures.Tests.Integration/Docker/Fixtures/DockerEnvironmentFixtureTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Containers/ContainerTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Fixtures/DockerEnvironmentFixtureTests.cs, Mittons.Fixtures.Tests.Unit/Extensions/StringExtensionsTests.cs, Mittons.Fixtures/Docker/Attributes/Run.cs, Mittons.Fixtures/Docker/Containers/Container.cs, Mittons.Fixtures/Docker/Fixtures/DockerEnvironmentFixture.cs, Mittons.Fixtures/Docker/Networks/DefaultNetwork.cs, Mittons.Fixtures/Extensions/StringExtensions.cs
Added boolean, which defaults to true, so you can set the run to not teardown when you're done running.
Address #75
=> Updated the run attribute to accept a boolean for when to teardown

Mittons.Fixtures/README.md, README.md
Added a section for showing everybody who has contributed. We'll still want to add sections for maintainers/approvers, but since I'm not sure I have the permissions set up properly, I don't want to do that prematurely.
Addresses #19
=> Add contributors section

Mittons.Fixtures.Tests.Integration/Docker/Gateways/ContainerGatewayTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Containers/ContainerTests.cs, Mittons.Fixtures.Tests.Unit/Docker/Containers/SftpContainerTests.cs, Mittons.Fixtures/Docker/Containers/Container.cs, Mittons.Fixtures/Docker/Containers/SftpContainer.cs, Mittons.Fixtures/Docker/Gateways/ContainerGateway.cs, Mittons.Fixtures/Docker/Gateways/IContainerGateway.cs
Added ability to empty directories, this allows for easy cleanup at the end of tests.
=> Added ability to empty directories

Mittons.Fixtures.Tests.Unit/Core/DependencyGraphTests.cs, Mittons.Fixtures/Core/DependencyGraph.cs
=> small optimization to the dependency graph to remove unnecessary check

Mittons.Fixtures.Tests.Integration/Containers/Gateways/Docker/ContainerGatewayTests.cs, Mittons.Fixtures/Containers/Gateways/Docker/ContainerGateway.cs
=> cleaned up the temp filename
